services: 
    web:
        hostname: web
        container_name: MarketBasketWeb
        build:
            dockerfile: php/Dockerfile

        volumes:
        - ./webserver_data/:/var/www/localhost/htdocs/

        ports:
            - "80:80"
        environment: 
            WEB_DOCUMENT_ROOT: /var/www/html

    database:
        hostname: sql
        container_name: MarketBasketSQL
        build:
            dockerfile: Dockerfile
        user: root
        
        ports:
            - "1433:1433"
        
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=BratwurstIN23!
            - MSSQL_PID=Developer

        volumes:
            - ./mssql-data/:/var/opt/mssql
            - ./init/:/init


        command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'BratwurstIN23!' -d master -i /init/init.sql & sleep infinity"
  

    mongo:
        image: mongo
        container_name: MarketBasketMongo
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-data:/data/db

    sync:
        container_name: MarketBasketPython
        build: 
            context: .
            dockerfile: sync/Dockerfile
        depends_on:
            - database
            - mongo
        volumes:
            - ./sync/syncScript:/app
        environment:
            MSSQL_HOST: database
            MSSQL_USER: SA
            MSSQL_PASSWORD: "BratwurstIN23!"
            MSSQL_DB: TestDB
            MONGO_URI: "mongodb://mongo:27017/"
        restart: always